# Load Airports

Load airports from `airline_routes.json` into a pandas DataFrame.

In [1]:
import pandas as pd
url = 'https://raw.githubusercontent.com/Jonty/airline-route-data/refs/heads/main/airline_routes.json'
routes = pd.read_json(url).transpose()
print(routes.shape)
routes.head(3)

/Users/jonzimmerman/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

(3889, 13)

,city_name,continent,country,country_code,display_name,elevation,iata,icao,latitude,longitude,name,routes,timezone
AAA,Anaa,OC,French Polynesia,PF,"Anaa (AAA), French Polynesia",23,AAA,NTGA,-17.355648,-145.50913,Anaa Airport,"[{'carriers': [{'iata': 'VT', 'name': 'Air Tah...",Pacific/Tahiti
AAD,Adado,AF,Somalia,SO,"Adado (AAD), Somalia",1005,AAD,None,6.095833,46.6375,Adado Airport,"[{'carriers': [], 'iata': 'MGQ', 'km': 474, 'm...",Africa/Mogadishu
AAE,Annaba,AF,Algeria,DZ,"Annaba (AAE), Algeria",16,AAE,DABB,36.821392,7.811857,Annaba,"[{'carriers': [{'iata': 'AH', 'name': 'Air Alg...",Africa/Algiers

In [2]:
import json

pdx = routes[routes['iata']=="PDX"]
routes_list = pdx["routes"].iloc[0]
pd.DataFrame(routes_list).head(3)

                                            carriers iata    km  min
0  [{'iata': 'AS', 'name': 'Alaska Airlines'}, {'...  SEA   207   65
1  [{'iata': 'AA', 'name': 'American Airlines'}, ...  LAX  1341  149
2  [{'iata': 'AA', 'name': 'American Airlines'}, ...  PHX  1624  159

In [3]:
dfs = []
for iata_code, row in routes.iterrows():
    routes_list = row["routes"]
    if not routes_list:
        continue
    df = pd.DataFrame(routes_list)
    df["dest_iata"] = iata_code
    dfs.append(df)
destinations = pd.concat(dfs, ignore_index=True)
destinations[destinations['iata']=="PDX"].head(3)

                                         carriers iata    km  min dest_iata
172   [{'iata': 'AS', 'name': 'Alaska Airlines'}]  PDX  1786  183       ABQ
2192              [{'iata': 'KL', 'name': 'KLM'}]  PDX  8052  605       AMS
2272  [{'iata': 'AS', 'name': 'Alaska Airlines'}]  PDX  2482  220       ANC

In [4]:
master_air_df = pd.merge(
    routes,
    destinations,
    on = 'iata'
)

print(routes.shape)
print(destinations.shape)
print(master_air_df.shape)

master_air_df[master_air_df['iata']=="PDX"].head(3)

(3889, 13)
(58707, 5)
(58707, 17)

,city_name,continent,country,country_code,display_name,elevation,iata,icao,latitude,longitude,name,routes,timezone,carriers,km,min,dest_iata
40152,Portland,NA,USA,US,"Portland (PDX), USA",30,PDX,KPDX,45.588995,-122.592901,Portland International,"[{'carriers': [{'iata': 'AS', 'name': 'Alaska ...",America/Los_Angeles,"[{'iata': 'AS', 'name': 'Alaska Airlines'}]",1786,183,ABQ
40153,Portland,NA,USA,US,"Portland (PDX), USA",30,PDX,KPDX,45.588995,-122.592901,Portland International,"[{'carriers': [{'iata': 'AS', 'name': 'Alaska ...",America/Los_Angeles,"[{'iata': 'KL', 'name': 'KLM'}]",8052,605,AMS
40154,Portland,NA,USA,US,"Portland (PDX), USA",30,PDX,KPDX,45.588995,-122.592901,Portland International,"[{'carriers': [{'iata': 'AS', 'name': 'Alaska ...",America/Los_Angeles,"[{'iata': 'AS', 'name': 'Alaska Airlines'}]",2482,220,ANC

Let's do a self-join to get the name of the destination airport

In [5]:
source_name = master_air_df[['name','iata']].drop_duplicates()
source_name = source_name.rename(
    columns={
        'name':'dest_name',
        'iata':'dest_iata'
    }
)

print(master_air_df.shape)
master_air_df = pd.merge(
    master_air_df,
    source_name,
    on = 'dest_iata',
    how = 'left'
)

print(source_name.shape)
print(master_air_df.shape)

master_air_df[master_air_df['iata']=="PDX"].head(3)

(58707, 17)
(3816, 2)
(58707, 18)

,city_name,continent,country,country_code,display_name,elevation,iata,icao,latitude,longitude,name,routes,timezone,carriers,km,min,dest_iata,dest_name
40152,Portland,NA,USA,US,"Portland (PDX), USA",30,PDX,KPDX,45.588995,-122.592901,Portland International,"[{'carriers': [{'iata': 'AS', 'name': 'Alaska ...",America/Los_Angeles,"[{'iata': 'AS', 'name': 'Alaska Airlines'}]",1786,183,ABQ,Albuquerque International Sunport
40153,Portland,NA,USA,US,"Portland (PDX), USA",30,PDX,KPDX,45.588995,-122.592901,Portland International,"[{'carriers': [{'iata': 'AS', 'name': 'Alaska ...",America/Los_Angeles,"[{'iata': 'KL', 'name': 'KLM'}]",8052,605,AMS,Schiphol
40154,Portland,NA,USA,US,"Portland (PDX), USA",30,PDX,KPDX,45.588995,-122.592901,Portland International,"[{'carriers': [{'iata': 'AS', 'name': 'Alaska ...",America/Los_Angeles,"[{'iata': 'AS', 'name': 'Alaska Airlines'}]",2482,220,ANC,Ted Stevens Anchorage International

In [6]:
# Count number of destinations per source airport, add as column "num_dests"
import numpy as np

dests_per_source = master_air_df["iata"].value_counts()
master_air_df["num_dests"] = master_air_df["iata"].map(dests_per_source)
master_air_df[["iata", "num_dests"]].drop_duplicates().sort_values("num_dests", ascending=False)
master_air_df['source_access_index'] = np.select(
    [
        master_air_df["num_dests"] < 10,
        (master_air_df["num_dests"] >= 10) & (master_air_df["num_dests"] < 25),
        (master_air_df["num_dests"] >= 25) & (master_air_df["num_dests"] < 50),
        (master_air_df["num_dests"] >= 50) & (master_air_df["num_dests"] < 100),
        master_air_df["num_dests"] >= 100,
    ],
    [1, 2, 3, 4, 5],
    default=np.nan,
)
master_air_df[master_air_df['iata']=="PDX"].head(3)

,city_name,continent,country,country_code,display_name,elevation,iata,icao,latitude,longitude,name,routes,timezone,carriers,km,min,dest_iata,dest_name,num_dests,source_access_index
40152,Portland,NA,USA,US,"Portland (PDX), USA",30,PDX,KPDX,45.588995,-122.592901,Portland International,"[{'carriers': [{'iata': 'AS', 'name': 'Alaska ...",America/Los_Angeles,"[{'iata': 'AS', 'name': 'Alaska Airlines'}]",1786,183,ABQ,Albuquerque International Sunport,87,4.0
40153,Portland,NA,USA,US,"Portland (PDX), USA",30,PDX,KPDX,45.588995,-122.592901,Portland International,"[{'carriers': [{'iata': 'AS', 'name': 'Alaska ...",America/Los_Angeles,"[{'iata': 'KL', 'name': 'KLM'}]",8052,605,AMS,Schiphol,87,4.0
40154,Portland,NA,USA,US,"Portland (PDX), USA",30,PDX,KPDX,45.588995,-122.592901,Portland International,"[{'carriers': [{'iata': 'AS', 'name': 'Alaska ...",America/Los_Angeles,"[{'iata': 'AS', 'name': 'Alaska Airlines'}]",2482,220,ANC,Ted Stevens Anchorage International,87,4.0

Let's do another self join to get the routes and access index from the sources to the desitnations

In [7]:
access_info = master_air_df[['iata','num_dests','source_access_index']].drop_duplicates()
access_info = access_info.rename(
    columns={
        'iata':'dest_iata',
        'num_dests':'dest_num_dests',
        'source_access_index':'dest_access_index'
    }
)

print(master_air_df.shape)
master_air_df = pd.merge(
    master_air_df,
    access_info,
    on = 'dest_iata',
    how = 'left'
)

print(access_info.shape)
print(master_air_df.shape)

master_air_df[master_air_df['iata']=="PDX"].head(3)

(58707, 20)
(3816, 3)
(58707, 22)

,city_name,continent,country,country_code,display_name,elevation,iata,icao,latitude,longitude,...,timezone,carriers,km,min,dest_iata,dest_name,num_dests,source_access_index,dest_num_dests,dest_access_index
40152,Portland,NA,USA,US,"Portland (PDX), USA",30,PDX,KPDX,45.588995,-122.592901,...,America/Los_Angeles,"[{'iata': 'AS', 'name': 'Alaska Airlines'}]",1786,183,ABQ,Albuquerque International Sunport,87,4.0,31.0,3.0
40153,Portland,NA,USA,US,"Portland (PDX), USA",30,PDX,KPDX,45.588995,-122.592901,...,America/Los_Angeles,"[{'iata': 'KL', 'name': 'KLM'}]",8052,605,AMS,Schiphol,87,4.0,270.0,5.0
40154,Portland,NA,USA,US,"Portland (PDX), USA",30,PDX,KPDX,45.588995,-122.592901,...,America/Los_Angeles,"[{'iata': 'AS', 'name': 'Alaska Airlines'}]",2482,220,ANC,Ted Stevens Anchorage International,87,4.0,50.0,4.0

### One more self join to get dest coordinates

In [8]:
dest_coords = master_air_df[['iata','latitude','longitude']].drop_duplicates()
dest_coords = dest_coords.rename(
    columns={
        'iata':'dest_iata',
        'latitude':'dest_latitude',
        'longitude':'dest_longitude'
    }
)

print(master_air_df.shape)
master_air_df = pd.merge(
    master_air_df,
    dest_coords,
    on = 'dest_iata',
    how = 'left'
)

print(dest_coords.shape)
print(master_air_df.shape)

master_air_df[master_air_df['iata']=="PDX"].head(3)

(58707, 22)
(3816, 3)
(58707, 24)

,city_name,continent,country,country_code,display_name,elevation,iata,icao,latitude,longitude,...,km,min,dest_iata,dest_name,num_dests,source_access_index,dest_num_dests,dest_access_index,dest_latitude,dest_longitude
40152,Portland,NA,USA,US,"Portland (PDX), USA",30,PDX,KPDX,45.588995,-122.592901,...,1786,183,ABQ,Albuquerque International Sunport,87,4.0,31.0,3.0,35.049625,-106.617193
40153,Portland,NA,USA,US,"Portland (PDX), USA",30,PDX,KPDX,45.588995,-122.592901,...,8052,605,AMS,Schiphol,87,4.0,270.0,5.0,52.309069,4.763385
40154,Portland,NA,USA,US,"Portland (PDX), USA",30,PDX,KPDX,45.588995,-122.592901,...,2482,220,ANC,Ted Stevens Anchorage International,87,4.0,50.0,4.0,61.174444,-149.996389

# Connectivity Index

In [9]:
import numpy as np

# Source term: for each source airport, (num_dests * source_access_index)
master_air_df['source_term'] = (master_air_df["num_dests"] * master_air_df["source_access_index"])
# Destination sum: for each source, sum over its 87 (or N) routes of (dest_num_dests * dest_access_index)
master_air_df['dest_sum'] = (master_air_df["dest_num_dests"] * master_air_df["dest_access_index"])#.groupby(master_air_df["iata"]).sum()
master_air_df["dest_term"] = master_air_df["iata"].map(master_air_df.groupby("iata")["dest_sum"].sum())# # Normalize to 0-100
master_air_df['connect_term_unnorm'] = (np.log1p(master_air_df['source_term']) *0.75) + (np.log1p(master_air_df['dest_term'])*0.25)
master_air_df["connectivity_index"] = (master_air_df["connect_term_unnorm"] - master_air_df["connect_term_unnorm"].min()) / (master_air_df["connect_term_unnorm"].max() - master_air_df["connect_term_unnorm"].min()) * 100

master_air_df[master_air_df['iata']=="PDX"].head(3)

,city_name,continent,country,country_code,display_name,elevation,iata,icao,latitude,longitude,...,source_access_index,dest_num_dests,dest_access_index,dest_latitude,dest_longitude,source_term,dest_sum,dest_term,connect_term_unnorm,connectivity_index
40152,Portland,NA,USA,US,"Portland (PDX), USA",30,PDX,KPDX,45.588995,-122.592901,...,4.0,31.0,3.0,35.049625,-106.617193,348.0,93.0,33960.0,6.999546,81.985526
40153,Portland,NA,USA,US,"Portland (PDX), USA",30,PDX,KPDX,45.588995,-122.592901,...,4.0,270.0,5.0,52.309069,4.763385,348.0,1350.0,33960.0,6.999546,81.985526
40154,Portland,NA,USA,US,"Portland (PDX), USA",30,PDX,KPDX,45.588995,-122.592901,...,4.0,50.0,4.0,61.174444,-149.996389,348.0,200.0,33960.0,6.999546,81.985526

In [11]:
what_did_i_do = master_air_df[['iata','name','num_dests','connectivity_index']]
what_did_i_do = what_did_i_do.sort_values('connectivity_index', ascending=False).drop_duplicates()
what_did_i_do.head(25)

,iata,name,num_dests,connectivity_index
24980,IST,Istanbul Airport,314,100.000000
19008,FRA,Frankfurt Airport,284,99.345819
9643,CDG,Charles De Gaulle,272,98.936872
2061,AMS,Schiphol,270,98.746107
16081,DXB,Dubai International Airport,268,98.252921
18053,FCO,Fiumicino,245,97.705130
39074,ORD,Chicago O Hare International,278,97.497672
32337,MAD,Barajas,232,96.952286
35666,MUC,Munich Airport,230,96.913056
14212,DFW,Dallas Fort Worth International,272,96.903471
30392,LHR,Heathrow,222,96.790521
4154,BCN,El Prat Airport,226,96.605210
3151,ATL,Hartsfield–Jackson Atlanta International Airport,245,96.172968
58300,ZRH,Zurich Airport,216,96.124716
42909,PVG,Shanghai Pudong International Airport,234,95.953562
35870,MXP,Milan Malpensa Airport,212,95.900127
53902,VIE,Vienna International Airport,206,95.641870
15675,DUB,Dublin Airport,204,95.506694
30161,LGW,Gatwick,212,95.379439
25840,JFK,John F Kennedy International,204,95.229162
11994,CPH,Copenhagen Airport,198,95.078121
40376,PEK,Beijing Capital International Airport,213,95.007650
13801,DEN,Denver International,236,94.823456
32802,MAN,Manchester Airport,197,94.665500
57699,YYZ,Pearson International,193,94.394681

In [12]:
what_did_i_do[what_did_i_do['iata']=="CEC"]

     iata                      name  num_dests  connectivity_index
9759  CEC  Del Norte County Airport          2           18.687228

### Redundancy Index

In [13]:
import numpy as np

def haversine_miles(lat1, lon1, lat2, lon2):
    R = 3959  # Earth radius in miles
    lat1, lon1, lat2, lon2 = np.radians(lat1), np.radians(lon1), np.radians(lat2), np.radians(lon2)
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))
    return R * c

In [15]:
# 1. Unique airports - ensure we have one row per airport and valid coords
airports = master_air_df[["iata", "latitude", "longitude"]].drop_duplicates(subset="iata")
airports["latitude"] = pd.to_numeric(airports["latitude"], errors="coerce")
airports["longitude"] = pd.to_numeric(airports["longitude"], errors="coerce")
airports = airports.dropna(subset=["latitude", "longitude"]).reset_index(drop=True)

n = len(airports)
lats = airports["latitude"].values
lons = airports["longitude"].values

# 2. Compute distances (loop uses same n as airports)
nearest_mi = []
within_10 = []
within_25 = []
within_50 = []
within_100 = []
within_250 = []
within_500 = []

for i in range(n):
    dists = haversine_miles(lats[i], lons[i], lats, lons)
    dists[i] = np.inf  # exclude self
    nearest_mi.append(np.min(dists))
    within_10.append(np.sum(dists <= 10))
    within_25.append(np.sum(dists <= 25))
    within_50.append(np.sum(dists <= 50))
    within_100.append(np.sum(dists <= 100))
    within_250.append(np.sum(dists <= 250))
    within_500.append(np.sum(dists <= 500))

# 3. Assign (list lengths must match n)
airports["nearest_airport_miles"] = nearest_mi
airports["airports_within_10_mi"] = within_10
airports["airports_within_25_mi"] = within_25
airports["airports_within_50_mi"] = within_50
airports["airports_within_100_mi"] = within_100
airports["airports_within_250_mi"] = within_250
airports["airports_within_500_mi"] = within_500

In [16]:
# Keep only the new columns when merging
dist_cols = ["nearest_airport_miles", "airports_within_10_mi", "airports_within_25_mi", 
             "airports_within_50_mi", "airports_within_100_mi", "airports_within_250_mi", "airports_within_500_mi"]
print(master_air_df.shape)
master_air_df = master_air_df.merge(airports[["iata"] + dist_cols], on="iata", how="left")
print(master_air_df.shape)

(58707, 29)
(58707, 36)

In [17]:
# Aggregate to one row per origin airport
origins = master_air_df.groupby("iata").agg(
    nearest_airport_miles=("nearest_airport_miles", "first"),
    airports_within_10_mi=("airports_within_10_mi", "first"),
    airports_within_25_mi=("airports_within_25_mi", "first"),
    airports_within_50_mi=("airports_within_50_mi", "first"),
    airports_within_100_mi=("airports_within_100_mi", "first"),
    airports_within_250_mi=("airports_within_250_mi", "first"),
    airports_within_500_mi=("airports_within_500_mi", "first"),
    connectivity_index=("connectivity_index", "first"),
    avg_route_miles=("km", "min"),  # will convert to miles below
).reset_index()

origins["avg_route_miles"] = origins["avg_route_miles"] * 0.621371
origins.head(3)

,iata,nearest_airport_miles,airports_within_10_mi,airports_within_25_mi,airports_within_50_mi,airports_within_100_mi,airports_within_250_mi,airports_within_500_mi,connectivity_index,avg_route_miles
0,AAA,47.636981,0,0,1,2,19,36,15.009052,270.917756
1,AAD,71.655714,0,0,0,1,3,14,10.425310,294.529854
2,AAE,75.855542,0,0,0,2,15,63,51.098617,235.499609

In [18]:
# Components (higher = more redundancy)
origins["c1"] = 1 / (1 + origins["nearest_airport_miles"])
origins["c2"] = np.log1p(
    (4 * origins["airports_within_10_mi"]) +
    (3 * origins["airports_within_25_mi"]) +
    (2 * origins["airports_within_50_mi"]) +
    (1 * origins["airports_within_100_mi"]) +
    (0.5 * origins["airports_within_250_mi"]) +
    (0.25 * origins["airports_within_500_mi"])
)
origins["c3"] = 1 / (1 + origins["avg_route_miles"])
origins["c4"] = origins["connectivity_index"]
origins.head(3)

,iata,nearest_airport_miles,airports_within_10_mi,airports_within_25_mi,airports_within_50_mi,airports_within_100_mi,airports_within_250_mi,airports_within_500_mi,connectivity_index,avg_route_miles,c1,c2,c3,c4
0,AAA,47.636981,0,0,1,2,19,36,15.009052,270.917756,0.020560,3.157000,0.003678,15.009052
1,AAD,71.655714,0,0,0,1,3,14,10.425310,294.529854,0.013764,1.945910,0.003384,10.425310
2,AAE,75.855542,0,0,0,2,15,63,51.098617,235.499609,0.013011,3.267666,0.004228,51.098617

In [19]:
# Min-max normalize
for col in ["c1", "c2", "c3", "c4"]:
    lo, hi = origins[col].min(), origins[col].max()
    origins[col + "_n"] = (origins[col] - lo) / (hi - lo) if hi > lo else 0.5

# Weighted score
weights = [0.25, 0.30, 0.20, 0.25]
origins["redundancy_score"] = (
    weights[0] * origins["c1_n"]
    + weights[1] * origins["c2_n"]
    + weights[2] * origins["c3_n"]
    + weights[3] * origins["c4_n"]
)

lo = origins["redundancy_score"].min()
hi = origins["redundancy_score"].max()
origins["redundancy_score"] = (origins["redundancy_score"] - lo) / (hi - lo) * 100 if hi > lo else 50


origins.head(3)

,iata,nearest_airport_miles,airports_within_10_mi,airports_within_25_mi,airports_within_50_mi,airports_within_100_mi,airports_within_250_mi,airports_within_500_mi,connectivity_index,avg_route_miles,c1,c2,c3,c4,c1_n,c2_n,c3_n,c4_n,redundancy_score
0,AAA,47.636981,0,0,1,2,19,36,15.009052,270.917756,0.020560,3.157000,0.003678,15.009052,0.020416,0.699441,0.003439,0.150091,32.460289
1,AAD,71.655714,0,0,0,1,3,14,10.425310,294.529854,0.013764,1.945910,0.003384,10.425310,0.013458,0.431121,0.003145,0.104253,19.998421
2,AAE,75.855542,0,0,0,2,15,63,51.098617,235.499609,0.013011,3.267666,0.004228,51.098617,0.012688,0.723960,0.003990,0.510986,45.188514

In [20]:
master_air_df = master_air_df.merge(origins[["iata", "redundancy_score"]], on="iata", how="left")
master_air_df.head(3)

,city_name,continent,country,country_code,display_name,elevation,iata,icao,latitude,longitude,...,connect_term_unnorm,connectivity_index,nearest_airport_miles,airports_within_10_mi,airports_within_25_mi,airports_within_50_mi,airports_within_100_mi,airports_within_250_mi,airports_within_500_mi,redundancy_score
0,Anaa,OC,French Polynesia,PF,"Anaa (AAA), French Polynesia",23,AAA,NTGA,-17.355648,-145.50913,...,1.706093,15.009052,47.636981,0,0,1,2,19,36,32.460289
1,Adado,AF,Somalia,SO,"Adado (AAD), Somalia",1005,AAD,None,6.095833,46.6375,...,1.343820,10.425310,71.655714,0,0,0,1,3,14,19.998421
2,Annaba,AF,Algeria,DZ,"Annaba (AAE), Algeria",16,AAE,DABB,36.821392,7.811857,...,4.558414,51.098617,75.855542,0,0,0,2,15,63,45.188514

In [21]:
# Save master_air_df as parquet (saves space vs CSV/JSON)
master_air_df.to_parquet("master_air.parquet", index=False)

In [22]:
master_air_df

,city_name,continent,country,country_code,display_name,elevation,iata,icao,latitude,longitude,...,connect_term_unnorm,connectivity_index,nearest_airport_miles,airports_within_10_mi,airports_within_25_mi,airports_within_50_mi,airports_within_100_mi,airports_within_250_mi,airports_within_500_mi,redundancy_score
0,Anaa,OC,French Polynesia,PF,"Anaa (AAA), French Polynesia",23,AAA,NTGA,-17.355648,-145.50913,...,1.706093,15.009052,47.636981,0,0,1,2,19,36,32.460289
1,Adado,AF,Somalia,SO,"Adado (AAD), Somalia",1005,AAD,None,6.095833,46.6375,...,1.343820,10.425310,71.655714,0,0,0,1,3,14,19.998421
2,Annaba,AF,Algeria,DZ,"Annaba (AAE), Algeria",16,AAE,DABB,36.821392,7.811857,...,4.558414,51.098617,75.855542,0,0,0,2,15,63,45.188514
3,Annaba,AF,Algeria,DZ,"Annaba (AAE), Algeria",16,AAE,DABB,36.821392,7.811857,...,4.558414,51.098617,75.855542,0,0,0,2,15,63,45.188514
4,Annaba,AF,Algeria,DZ,"Annaba (AAE), Algeria",16,AAE,DABB,36.821392,7.811857,...,4.558414,51.098617,75.855542,0,0,0,2,15,63,45.188514
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58702,Sylhet,AS,Bangladesh,BD,"Sylhet (ZYL), Bangladesh",50,ZYL,VGSY,24.9632,91.866798,...,4.505340,50.427077,51.699391,0,0,0,5,28,67,48.249481
58703,Sylhet,AS,Bangladesh,BD,"Sylhet (ZYL), Bangladesh",50,ZYL,VGSY,24.9632,91.866798,...,4.505340,50.427077,51.699391,0,0,0,5,28,67,48.249481
58704,Sylhet,AS,Bangladesh,BD,"Sylhet (ZYL), Bangladesh",50,ZYL,VGSY,24.9632,91.866798,...,4.505340,50.427077,51.699391,0,0,0,5,28,67,48.249481
58705,Sylhet,AS,Bangladesh,BD,"Sylhet (ZYL), Bangladesh",50,ZYL,VGSY,24.9632,91.866798,...,4.505340,50.427077,51.699391,0,0,0,5,28,67,48.249481
58706,Tymovskoye,EU,Russia,RU,"Tymovskoye (ZZO), Russia",479,ZZO,UHSO,50.666668,142.75,...,1.422590,11.421966,29.013058,0,0,1,2,6,20,26.475410